version: "3.9"
services:
  jellyfin:
    build: ./jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./movies:/opt/jellyfin/movies
      - jellyfinData:/opt/jellyfin/data
      - jellyfinCache:/opt/jellyfin/cache
      - jellyfinConfig:/opt/jellyfin/config
      - jellyfinLog:/opt/jellyfin/log

volumes:
  jellyfinData:
  jellyfinCache:
  jellyfinConfig:
  jellyfinLog: