version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - type: volume
        source: jellyfinSsl
        target: /ssl
    depends_on: 
      - jellyfin
  jellyfin:
    build: ./jellyfin
    volumes:
      - type: volume
        source: jellyfinDB
        target: /var/lib/jellyfin
      - type: volume
        source: jellyfinWeb
        target: /usr/share/jellyfin/web
      - type: volume
        source: jellyfinSsl
        target: /ssl
      - type: bind
        source: /Media
        target: /Media

volumes:
  jellyfinDB:
  jellyfinWeb:
  jellyfinSsl: