services:
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - "jellyfin_config:/config"
      - "jellyfin_cache:/cache"
    ports:
      - "8096:8096"

volumes:
  jellyfin_config:
  jellyfin_cache: