Vagrant.configure("2") do |config|

  config.vm.box = "../packer/output-jellyfin/package.box"
  config.vm.network "forwarded_port", guest: 8096, host:8096

  config.vm.provision "shell",
    inline: "cd /docker && sudo docker compose up -d"

end
